/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PresetsRouteImport } from './routes/presets'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as BenchmarksRouteImport } from './routes/benchmarks'
import { Route as IndexRouteImport } from './routes/index'

const PresetsRoute = PresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRoute
  '/builder': typeof BuilderRoute
  '/compare': typeof CompareRoute
  '/guides': typeof GuidesRoute
  '/presets': typeof PresetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRoute
  '/builder': typeof BuilderRoute
  '/compare': typeof CompareRoute
  '/guides': typeof GuidesRoute
  '/presets': typeof PresetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRoute
  '/builder': typeof BuilderRoute
  '/compare': typeof CompareRoute
  '/guides': typeof GuidesRoute
  '/presets': typeof PresetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/benchmarks'
    | '/builder'
    | '/compare'
    | '/guides'
    | '/presets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/benchmarks' | '/builder' | '/compare' | '/guides' | '/presets'
  id:
    | '__root__'
    | '/'
    | '/benchmarks'
    | '/builder'
    | '/compare'
    | '/guides'
    | '/presets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenchmarksRoute: typeof BenchmarksRoute
  BuilderRoute: typeof BuilderRoute
  CompareRoute: typeof CompareRoute
  GuidesRoute: typeof GuidesRoute
  PresetsRoute: typeof PresetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/presets': {
      id: '/presets'
      path: '/presets'
      fullPath: '/presets'
      preLoaderRoute: typeof PresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenchmarksRoute: BenchmarksRoute,
  BuilderRoute: BuilderRoute,
  CompareRoute: CompareRoute,
  GuidesRoute: GuidesRoute,
  PresetsRoute: PresetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
